package com.hemendra.mdmgenerator.model;

/**
 * @author Hemendra
 */
public class ColumnIdentity {
    private boolean primaryKey;
    private boolean autoGenerated;
    private String generationStartegy;

    public boolean isPrimaryKey() {
        return primaryKey;
    }

    public void setPrimaryKey(boolean primaryKey) {
        this.primaryKey = primaryKey;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public String getGenerationStartegy() {
        return generationStartegy;
    }

    public void setGenerationStartegy(String generationStartegy) {
        this.generationStartegy = generationStartegy;
    }
}
